// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace AppPrivy.Domain
{
    [Table("Author", Schema = "Blog")]
    //[Index(nameof(Email), Name = "uq_email", IsUnique = true)]
    //[Index(nameof(Mobile), Name = "uq_mobile", IsUnique = true)]
    public partial class Author
    {
        public Author()
        {
            Post = new HashSet<Post>();
        }

        [Key]
        public long AuthorId { get; set; }
        [StringLength(150)]
        public string Name { get; set; }
        [StringLength(15)]
        public string Mobile { get; set; }
        [StringLength(50)]
        public string Email { get; set; }
        [Required]
        [StringLength(32)]
        public string PasswordHash { get; set; }
        public DateTime RegisteredAt { get; set; }
        public DateTime? LastLogin { get; set; }
        [StringLength(255)]
        public string Intro { get; set; }
        public string Profile { get; set; }
        [StringLength(255)]
        public string UrlImage { get; set; }

        [InverseProperty("Author")]
        public virtual ICollection<Post> Post { get; set; }
    }
}