// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace AppPrivy.Domain
{
    [Table("PostMeta", Schema = "Blog")]
    //[Index(nameof(PostId), Name = "idx_meta_post")]
    //[Index(nameof(PostId), Name = "uq_post_meta", IsUnique = true)]
    public partial class PostMeta
    {
        [Key]
        public long PostMetaId { get; set; }
        public long PostId { get; set; }
        [Required]
        [StringLength(50)]
        public string Nkey { get; set; }
        [StringLength(500)]
        public string Content { get; set; }

        [ForeignKey(nameof(PostId))]
        [InverseProperty("PostMeta")]
        public virtual Post Post { get; set; }
    }
}