// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace AppPrivy.Domain
{
    [Table("PostTag", Schema = "Blog")]
    public partial class PostTag
    {
        [Key]
        public long PostId { get; set; }
        [Key]
        public long TagId { get; set; }
    }
}