// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace AppPrivy.Domain
{
    [Table("PostCategory", Schema = "Blog")]
    //[Index(nameof(CategoryId), Name = "idx_pc_category")]
    //[Index(nameof(PostId), Name = "idx_pc_post")]
    public partial class PostCategory
    {
        [Key]
        public long PostId { get; set; }
        [Key]
        public long CategoryId { get; set; }

        [ForeignKey(nameof(CategoryId))]
        [InverseProperty("PostCategory")]
        public virtual Category Category { get; set; }
        [ForeignKey(nameof(PostId))]
        [InverseProperty("PostCategory")]
        public virtual Post Post { get; set; }
    }
}