//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppPrivy.CrossCutting.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Constants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Constants() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppPrivy.CrossCutting.Resources.Constants", typeof(Constants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppPrivy.WebAppMvc.
        /// </summary>
        public static string AppPrivy_WebAppMvc {
            get {
                return ResourceManager.GetString("AppPrivy_WebAppMvc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppPrivyContext.
        /// </summary>
        public static string AppPrivyContext {
            get {
                return ResourceManager.GetString("AppPrivyContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppPrivyContextKey.
        /// </summary>
        public static string AppPrivyContextKey {
            get {
                return ResourceManager.GetString("AppPrivyContextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logs/AppPrivyLog.log.
        /// </summary>
        public static string AppPrivyLogFolderPath {
            get {
                return ResourceManager.GetString("AppPrivyLogFolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppPrivy.Cookie.
        /// </summary>
        public static string AuthenticationCookieName {
            get {
                return ResourceManager.GetString("AuthenticationCookieName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrador.
        /// </summary>
        public static string GrupoAdministrador {
            get {
                return ResourceManager.GetString("GrupoAdministrador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        public static string GrupoBlog {
            get {
                return ResourceManager.GetString("GrupoBlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistemas.
        /// </summary>
        public static string GrupoSistemas {
            get {
                return ResourceManager.GetString("GrupoSistemas", resourceCulture);
            }
        }
    }
}
